---
name: main

on:
  push:
    branches: [ "master" ]
    tags: ['*']
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    if: "!contains(github.event.commits[0].message, 'ci skip')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: 'Check changed files'
      id: changed-files
      uses: tj-actions/changed-files@v47
      with:
        files: |
          **.yaml

    - name: 'Update SM if updated'
      if: steps.changed-files.outputs.any_changed == 'true'
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        OUCHAN_CI_PROD_SA_JSON: ${{ secrets.OUCHAN_CI_PROD_SA_JSON }}
      run: |
        for file in ${ALL_CHANGED_FILES}; do
          if [[ "$file" == "permissions.yaml" ]]; then
            echo "$file was changed"
            SVC_ACCT_JSON=/tmp/ouchan-ci-sa.json
            echo "$OUCHAN_CI_PROD_SA_JSON" > $SVC_ACCT_JSON
            gcloud auth activate-service-account --key-file $SVC_ACCT_JSON
            if ! gcloud secrets versions access latest --secret rbac-permissions-yaml --project mobingi-main > /dev/null 2>&1; then
              gcloud secrets create rbac-permissions-yaml --project mobingi-main
            fi
            gcloud secrets versions add rbac-permissions-yaml --data-file "$file" --project mobingi-main
          fi
        done
