---
name: main

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    if: "!contains(github.event.commits[0].message, 'ci skip')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: 'Check changed files'
      id: changed-files
      uses: tj-actions/changed-files@v47
      with:
        files: |
          **.yaml

    - name: 'Update SM if updated'
      if: steps.changed-files.outputs.any_changed == 'true'
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        OUCHAN_CI_PROD_SA_JSON: ${{ secrets.OUCHAN_CI_PROD_SA_JSON }}
      run: |
        for file in ${ALL_CHANGED_FILES}; do
          if [[ "$file" == "permissions.yaml" ]]; then
            SECRET=rbac-permissions-yaml
            SVC_ACCT_JSON=/tmp/ouchan-ci-sa.json
            echo "$OUCHAN_CI_PROD_SA_JSON" > $SVC_ACCT_JSON
            gcloud auth activate-service-account --key-file $SVC_ACCT_JSON
            if ! gcloud secrets versions access latest --secret $SECRET --project mobingi-main > /dev/null 2>&1; then
              gcloud secrets create $SECRET --project mobingi-main
            fi
            gcloud secrets versions add $SECRET --data-file "$file" --project mobingi-main
            # Delete previous versions; SM is priced by versions.
            PREV_VER_URI=$(gcloud secrets versions list $SECRET --filter "state=ENABLED" --sort-by "~createTime" --limit 2 --uri --project mobingi-main | tail -n 1)
            DELIMITER="/"
            LAST_VER=$(echo "$PREV_VER_URI" | awk -F "$DELIMITER" '{print $NF}')
            gcloud secrets versions destroy $LAST_VER --secret $SECRET --project mobingi-main --quiet
          fi
        done
